# Generated by Django 4.0.6 on 2022-07-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_of_time',
            field=models.DateField(auto_now=True),
        ),
    ]
