# Generated by Django 4.0.6 on 2022-07-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_of_time',
            field=models.DateField(),
        ),
    ]
